### ISSUE TITLE
Files not well formed

### ISSUE THREAD

**Issue by whanley** [dig-eg-gaz/content#110]
There are 18 xml files that are not well formed, and can't be searched. Please fix these asap.

2 of these problems are my own fault! I'll fix them.

@karahofmeister 1905-01-07.xml
Description: Could not execute XPath on '1905-01-07.xml': The element type "div" must be terminated by the matching end-tag "</div>".

@courtneyelon 1905-03-29p3.xml
Description: Could not execute XPath on '1905-03-29p3.xml': Attribute name "Coyle" associated with an element type "Courtney" must be followed by the ' = ' character.
Please also rename this file as 1905-03-29.xml (remove the p3).

@MelizzaBlack 1905-08-08.xml 1905-08-08.xml 1905-08-08.xml 1905-08-08.xml 1905-08-08.xml
Description: Could not execute XPath on '1905-08-08.xml': The processing instruction target matching "[xX][mM][lL]" is not allowed.

@Lionex 1905-10-04.xml
Description: Could not execute XPath on '1905-10-04.xml': The content of elements must consist of well-formed character data or markup.

@bjv15 1905-10-17.xml
Description: Could not execute XPath on '1905-10-17.xml': The entity name must immediately follow the '&' in the entity reference.

@jhannaeugenio 1905-10-23.xml
Description: Could not execute XPath on '1905-10-23.xml': The processing instruction target matching "[xX][mM][lL]" is not allowed.

@jhannaeugenio 1905-10-25.xml
Description: Could not execute XPath on '1905-10-25.xml': The element type "div" must be terminated by the matching end-tag "</div>".

@jhannaeugenio 1905-10-26.xml
Description: Could not execute XPath on '1905-10-26.xml': Attribute name "FROM" associated with an element type "DEPARTURE" must be followed by the ' = ' character.

@jhannaeugenio 1905-10-27.xml 1905-10-28.xml
Description: Could not execute XPath on '1905-10-27.xml': The entity name must immediately follow the '&' in the entity reference.

@CelitaS 1905-12-28.xml 1905-12-29.xml
Description: Could not execute XPath on '1905-12-28.xml': The entity name must immediately follow the '&' in the entity reference.

**Comment by whanley** [comment]
Okay, I've fixed mine now. 2 down, 16 to go!

**Comment by Lionex** [comment]
I think the issue is the french; I used the accents and ligatures for ae;
are they not allowed in XML documents?

**Comment by Lionex** [comment]
@whanley I think the issue is the french; I used the accents like `é` and ligatures for `æ`;
are they not allowed in XML documents?

**Comment by whanley** [comment]
Will Hanley
Department of History, Florida State University
417 Bellamy Building, 137 Collegiate Loop
Tallahassee, Florida 32306-2200
prosop.org

**Comment by whanley** [comment]
@Lionex The problem is not the character set. There were some weird divs that I could see in oxygen, so I fixed them--the file now works for search. Please pull this updated version from the organization repo. 
I noticed that most of your files don't contain the updated schema reference on line 2. It should contain the word "out", thus: `<?xml-model href="https://raw.githubusercontent.com/dig-eg-gaz/resources/master/out/egSchema.rnc" type="application/relax-ng-compact-syntax"?>`

**Comment by whanley** [comment]
@courtneyelon I fixed your 1905-03-29.xml. 
@bjv15 I fixed your 1905-10-17.xml.
Please download these corrected versions if you are doing further editing. 

@MelizzaBlack there are some problems with your files--I'll help you in class.
@CelitaS there is a problem with the & symbols in your files. I can help.
