### ISSUE TITLE
Missing Advertisement

### ISSUE THREAD

**Issue by AlexisFitz** [dig-eg-gaz/content#605]
There is no ad for "The Upper Egypt Hotels Company" 
![image](https://user-images.githubusercontent.com/35302937/35589484-fe83edc4-05d1-11e8-9e6a-d004426feab5.png)

**Comment by whanley** [comment]
Link: [https://dig-eg-gaz.github.io/advertisements/#ueh01-upper-egypt-hotels](https://dig-eg-gaz.github.io/advertisements/#ueh01-upper-egypt-hotels)
