### ISSUE TITLE
Missing Advertisement/different language

### ISSUE THREAD

**Issue by AlexisFitz** [dig-eg-gaz/content#606]
The advertisement for "Carpets" doesn't exist and the ad above it is in a different language and I don't remember if I am supposed to put that into the issues tab as well. 
![image](https://user-images.githubusercontent.com/35302937/35590888-2f9ebe58-05d6-11e8-8619-2a3173cce430.png)

**Comment by whanley** [comment]
[Carpets](https://dig-eg-gaz.github.io/advertisements/#tas02-carpets-t-a-spartali--co)
[Les bebes](https://dig-eg-gaz.github.io/advertisements/#ems05-emulsion-scott---les-b%C3%A9b%C3%A9s-d%C3%A9p%C3%A9rissent-tout-comme-les-fleurs)
